// Code generated by protoc-gen-go.
// source: binggo.proto
// DO NOT EDIT!

/*
Package binggo is a generated protocol buffer package.

It is generated from these files:
	binggo.proto

It has these top-level messages:
	BMessage
	Head
	Body
	ResponseCode
	HeartBeatRequest
	HeartBeatResponse
*/
package binggo

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type MessageType int32

const (
	MessageType_HEART_BEAT_REQUEST  MessageType = 1
	MessageType_HEART_BEAT_RESPONSE MessageType = 2
)

var MessageType_name = map[int32]string{
	1: "HEART_BEAT_REQUEST",
	2: "HEART_BEAT_RESPONSE",
}
var MessageType_value = map[string]int32{
	"HEART_BEAT_REQUEST":  1,
	"HEART_BEAT_RESPONSE": 2,
}

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}
func (x MessageType) String() string {
	return proto.EnumName(MessageType_name, int32(x))
}
func (x *MessageType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(MessageType_value, data, "MessageType")
	if err != nil {
		return err
	}
	*x = MessageType(value)
	return nil
}
func (MessageType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type BMessage struct {
	Head             *Head  `protobuf:"bytes,1,req,name=head" json:"head,omitempty"`
	Body             *Body  `protobuf:"bytes,2,req,name=body" json:"body,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *BMessage) Reset()                    { *m = BMessage{} }
func (m *BMessage) String() string            { return proto.CompactTextString(m) }
func (*BMessage) ProtoMessage()               {}
func (*BMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *BMessage) GetHead() *Head {
	if m != nil {
		return m.Head
	}
	return nil
}

func (m *BMessage) GetBody() *Body {
	if m != nil {
		return m.Body
	}
	return nil
}

type Head struct {
	Version          *uint32 `protobuf:"varint,1,req,name=version" json:"version,omitempty"`
	SessionNo        *string `protobuf:"bytes,2,req,name=session_no" json:"session_no,omitempty"`
	MessageType      *int32  `protobuf:"varint,3,req,name=message_type" json:"message_type,omitempty"`
	Source           *uint32 `protobuf:"varint,4,req,name=source" json:"source,omitempty"`
	Dest             *uint32 `protobuf:"varint,5,opt,name=dest" json:"dest,omitempty"`
	CallPurpose      *string `protobuf:"bytes,6,opt,name=call_purpose" json:"call_purpose,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Head) Reset()                    { *m = Head{} }
func (m *Head) String() string            { return proto.CompactTextString(m) }
func (*Head) ProtoMessage()               {}
func (*Head) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Head) GetVersion() uint32 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

func (m *Head) GetSessionNo() string {
	if m != nil && m.SessionNo != nil {
		return *m.SessionNo
	}
	return ""
}

func (m *Head) GetMessageType() int32 {
	if m != nil && m.MessageType != nil {
		return *m.MessageType
	}
	return 0
}

func (m *Head) GetSource() uint32 {
	if m != nil && m.Source != nil {
		return *m.Source
	}
	return 0
}

func (m *Head) GetDest() uint32 {
	if m != nil && m.Dest != nil {
		return *m.Dest
	}
	return 0
}

func (m *Head) GetCallPurpose() string {
	if m != nil && m.CallPurpose != nil {
		return *m.CallPurpose
	}
	return ""
}

type Body struct {
	HeartBeatRequest  *HeartBeatRequest         `protobuf:"bytes,1,opt,name=heart_beat_request" json:"heart_beat_request,omitempty"`
	HeartBeatResponse *HeartBeatResponse        `protobuf:"bytes,2,opt,name=heart_beat_response" json:"heart_beat_response,omitempty"`
	XXX_extensions    map[int32]proto.Extension `json:"-"`
	XXX_unrecognized  []byte                    `json:"-"`
}

func (m *Body) Reset()                    { *m = Body{} }
func (m *Body) String() string            { return proto.CompactTextString(m) }
func (*Body) ProtoMessage()               {}
func (*Body) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

var extRange_Body = []proto.ExtensionRange{
	{1000, 536870911},
}

func (*Body) ExtensionRangeArray() []proto.ExtensionRange {
	return extRange_Body
}
func (m *Body) ExtensionMap() map[int32]proto.Extension {
	if m.XXX_extensions == nil {
		m.XXX_extensions = make(map[int32]proto.Extension)
	}
	return m.XXX_extensions
}

func (m *Body) GetHeartBeatRequest() *HeartBeatRequest {
	if m != nil {
		return m.HeartBeatRequest
	}
	return nil
}

func (m *Body) GetHeartBeatResponse() *HeartBeatResponse {
	if m != nil {
		return m.HeartBeatResponse
	}
	return nil
}

type ResponseCode struct {
	Retcode          *int32  `protobuf:"varint,1,req,name=retcode" json:"retcode,omitempty"`
	ErrorMessage     *string `protobuf:"bytes,2,opt,name=error_message" json:"error_message,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ResponseCode) Reset()                    { *m = ResponseCode{} }
func (m *ResponseCode) String() string            { return proto.CompactTextString(m) }
func (*ResponseCode) ProtoMessage()               {}
func (*ResponseCode) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ResponseCode) GetRetcode() int32 {
	if m != nil && m.Retcode != nil {
		return *m.Retcode
	}
	return 0
}

func (m *ResponseCode) GetErrorMessage() string {
	if m != nil && m.ErrorMessage != nil {
		return *m.ErrorMessage
	}
	return ""
}

type HeartBeatRequest struct {
	Payload          [][]byte `protobuf:"bytes,1,rep,name=payload" json:"payload,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *HeartBeatRequest) Reset()                    { *m = HeartBeatRequest{} }
func (m *HeartBeatRequest) String() string            { return proto.CompactTextString(m) }
func (*HeartBeatRequest) ProtoMessage()               {}
func (*HeartBeatRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *HeartBeatRequest) GetPayload() [][]byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

type HeartBeatResponse struct {
	Rc               *ResponseCode `protobuf:"bytes,1,req,name=rc" json:"rc,omitempty"`
	Payload          [][]byte      `protobuf:"bytes,2,rep,name=payload" json:"payload,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *HeartBeatResponse) Reset()                    { *m = HeartBeatResponse{} }
func (m *HeartBeatResponse) String() string            { return proto.CompactTextString(m) }
func (*HeartBeatResponse) ProtoMessage()               {}
func (*HeartBeatResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *HeartBeatResponse) GetRc() *ResponseCode {
	if m != nil {
		return m.Rc
	}
	return nil
}

func (m *HeartBeatResponse) GetPayload() [][]byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func init() {
	proto.RegisterType((*BMessage)(nil), "binggo.BMessage")
	proto.RegisterType((*Head)(nil), "binggo.Head")
	proto.RegisterType((*Body)(nil), "binggo.Body")
	proto.RegisterType((*ResponseCode)(nil), "binggo.ResponseCode")
	proto.RegisterType((*HeartBeatRequest)(nil), "binggo.HeartBeatRequest")
	proto.RegisterType((*HeartBeatResponse)(nil), "binggo.HeartBeatResponse")
	proto.RegisterEnum("binggo.MessageType", MessageType_name, MessageType_value)
}

var fileDescriptor0 = []byte{
	// 362 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x6c, 0x91, 0x4f, 0x4f, 0xc2, 0x40,
	0x10, 0xc5, 0xd3, 0x52, 0xfe, 0x74, 0x28, 0x5a, 0x17, 0xd4, 0xea, 0x89, 0xd4, 0x0b, 0xe1, 0xc0,
	0x81, 0x18, 0x8e, 0x26, 0xd4, 0xd4, 0x70, 0xf1, 0x1f, 0xd4, 0xf3, 0xa6, 0xb4, 0x1b, 0x24, 0xc1,
	0x6e, 0xdd, 0x6d, 0x4d, 0x38, 0xe9, 0xc7, 0xf5, 0x63, 0x38, 0xdd, 0x96, 0x44, 0xc4, 0x9e, 0xba,
	0x6f, 0xe6, 0xf7, 0x66, 0xde, 0x2e, 0x58, 0xcb, 0x75, 0xb2, 0x5a, 0xf1, 0x51, 0x2a, 0x78, 0xc6,
	0x49, 0xa3, 0x3c, 0xb9, 0x1e, 0xb4, 0xbc, 0x7b, 0x26, 0x65, 0xb8, 0x62, 0xe4, 0x12, 0x8c, 0x57,
	0x16, 0xc6, 0x8e, 0xd6, 0xd7, 0x07, 0xed, 0xb1, 0x35, 0xaa, 0x80, 0x19, 0x6a, 0x45, 0x6d, 0xc9,
	0xe3, 0xad, 0xa3, 0xef, 0xd7, 0x3c, 0xd4, 0xdc, 0x1c, 0x0c, 0xd5, 0x73, 0x0c, 0xcd, 0x0f, 0x26,
	0xe4, 0x9a, 0x27, 0xca, 0xa2, 0x43, 0x08, 0x80, 0x44, 0x6f, 0x14, 0x68, 0xc2, 0x15, 0x6a, 0x92,
	0x1e, 0x58, 0x6f, 0xe5, 0x3c, 0x9a, 0x6d, 0x53, 0xe6, 0xd4, 0x50, 0xad, 0x93, 0x23, 0x68, 0x48,
	0x9e, 0x8b, 0x88, 0x39, 0x86, 0x22, 0x2d, 0x30, 0x62, 0x26, 0x33, 0xa7, 0xde, 0xd7, 0xf0, 0x84,
	0x4c, 0x14, 0x6e, 0x36, 0x34, 0xcd, 0x45, 0xca, 0x25, 0x73, 0x1a, 0xa8, 0x9a, 0xee, 0x27, 0x18,
	0xc5, 0x78, 0x72, 0x0d, 0x04, 0xd7, 0x16, 0x19, 0x5d, 0xb2, 0x30, 0xa3, 0x82, 0xbd, 0xe7, 0x05,
	0xa9, 0x61, 0x4f, 0x7b, 0xec, 0xfc, 0x0a, 0x21, 0x32, 0x0f, 0x1b, 0xe6, 0x65, 0x9d, 0x4c, 0xa0,
	0xbb, 0x47, 0xc9, 0x94, 0x27, 0x68, 0xad, 0x2b, 0xec, 0xe2, 0x1f, 0xac, 0x6c, 0x18, 0x9a, 0xad,
	0xef, 0xa6, 0xfd, 0x85, 0x9f, 0xee, 0x4e, 0xc0, 0xda, 0xc9, 0xb7, 0x3c, 0x66, 0x45, 0x7e, 0xc1,
	0xb2, 0x08, 0x7f, 0x55, 0xfe, 0x3a, 0x39, 0x85, 0x0e, 0x13, 0x82, 0x0b, 0x5a, 0x25, 0x56, 0xee,
	0xa6, 0x7b, 0x05, 0xf6, 0xc1, 0x3a, 0xc8, 0xa6, 0xe1, 0x76, 0xc3, 0xd5, 0xf5, 0xd7, 0x06, 0x96,
	0x7b, 0x07, 0x27, 0x07, 0xc3, 0x49, 0x1f, 0x74, 0x11, 0x55, 0xef, 0xd3, 0xdb, 0xed, 0xf8, 0x77,
	0x87, 0x9d, 0x8f, 0x5e, 0xf8, 0x0c, 0x6f, 0xa0, 0x5d, 0xbd, 0x6f, 0x80, 0xd7, 0x4d, 0xce, 0x80,
	0xcc, 0xfc, 0xe9, 0x3c, 0xa0, 0x9e, 0x3f, 0x0d, 0xe8, 0xdc, 0x7f, 0x7e, 0xf1, 0x17, 0x81, 0xad,
	0x91, 0x73, 0xe8, 0xee, 0xe9, 0x8b, 0xa7, 0xc7, 0x87, 0x85, 0x6f, 0xeb, 0x3f, 0x01, 0x00, 0x00,
	0xff, 0xff, 0x2f, 0x5c, 0x40, 0xec, 0x37, 0x02, 0x00, 0x00,
}
