// Code generated by protoc-gen-go.
// source: demo.proto
// DO NOT EDIT!

/*
Package demo is a generated protocol buffer package.

It is generated from these files:
	demo.proto

It has these top-level messages:
	CallRequest
	CallResponse
*/
package demo

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type CallRequest struct {
	Person           *uint32 `protobuf:"varint,1,req,name=person" json:"person,omitempty"`
	Action           *string `protobuf:"bytes,3,req,name=action" json:"action,omitempty"`
	Mark             *string `protobuf:"bytes,4,opt,name=mark" json:"mark,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CallRequest) Reset()                    { *m = CallRequest{} }
func (m *CallRequest) String() string            { return proto.CompactTextString(m) }
func (*CallRequest) ProtoMessage()               {}
func (*CallRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CallRequest) GetPerson() uint32 {
	if m != nil && m.Person != nil {
		return *m.Person
	}
	return 0
}

func (m *CallRequest) GetAction() string {
	if m != nil && m.Action != nil {
		return *m.Action
	}
	return ""
}

func (m *CallRequest) GetMark() string {
	if m != nil && m.Mark != nil {
		return *m.Mark
	}
	return ""
}

type CallResponse struct {
	Retcode          *uint32 `protobuf:"varint,1,req,name=retcode" json:"retcode,omitempty"`
	Result           *string `protobuf:"bytes,2,opt,name=result" json:"result,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CallResponse) Reset()                    { *m = CallResponse{} }
func (m *CallResponse) String() string            { return proto.CompactTextString(m) }
func (*CallResponse) ProtoMessage()               {}
func (*CallResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CallResponse) GetRetcode() uint32 {
	if m != nil && m.Retcode != nil {
		return *m.Retcode
	}
	return 0
}

func (m *CallResponse) GetResult() string {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return ""
}

func init() {
	proto.RegisterType((*CallRequest)(nil), "demo.CallRequest")
	proto.RegisterType((*CallResponse)(nil), "demo.CallResponse")
}

var fileDescriptor0 = []byte{
	// 131 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0x49, 0xcd, 0xcd,
	0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x01, 0xb1, 0x95, 0xac, 0xb9, 0xb8, 0x9d, 0x13,
	0x73, 0x72, 0x82, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84, 0xf8, 0xb8, 0xd8, 0x0a, 0x52, 0x8b,
	0x8a, 0xf3, 0xf3, 0x24, 0x18, 0x15, 0x98, 0x34, 0x78, 0x41, 0xfc, 0xc4, 0xe4, 0x92, 0x4c, 0x20,
	0x9f, 0x19, 0xc8, 0xe7, 0x14, 0xe2, 0xe1, 0x62, 0xc9, 0x4d, 0x2c, 0xca, 0x96, 0x60, 0x51, 0x60,
	0xd4, 0xe0, 0x54, 0xd2, 0xe7, 0xe2, 0x81, 0x68, 0x2e, 0x2e, 0xc8, 0xcf, 0x2b, 0x4e, 0x15, 0xe2,
	0xe7, 0x62, 0x2f, 0x4a, 0x2d, 0x49, 0xce, 0x4f, 0x49, 0x45, 0x68, 0x2f, 0x4a, 0x2d, 0x2e, 0xcd,
	0x29, 0x91, 0x60, 0x02, 0x69, 0x00, 0x04, 0x00, 0x00, 0xff, 0xff, 0x2c, 0x83, 0x0d, 0x7e, 0x80,
	0x00, 0x00, 0x00,
}
