// Code generated by protoc-gen-go.
// source: service1.1000.2000.proto
// DO NOT EDIT!

/*
Package binggo_service1 is a generated protocol buffer package.

It is generated from these files:
	service1.1000.2000.proto

It has these top-level messages:
	SayHelloRequest
	SayHelloResponse
*/
package binggo_service1

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import binggo "."

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type MessageType int32

const (
	MessageType_BEGINNING_ID       MessageType = 1000
	MessageType_SAY_HELLO_REQUEST  MessageType = 1000
	MessageType_SAY_HELLO_RESPONSE MessageType = 1001
	MessageType_ENDING_ID          MessageType = 2000
)

var MessageType_name = map[int32]string{
	1000: "BEGINNING_ID",
	// Duplicate value: 1000: "SAY_HELLO_REQUEST",
	1001: "SAY_HELLO_RESPONSE",
	2000: "ENDING_ID",
}
var MessageType_value = map[string]int32{
	"BEGINNING_ID":       1000,
	"SAY_HELLO_REQUEST":  1000,
	"SAY_HELLO_RESPONSE": 1001,
	"ENDING_ID":          2000,
}

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}
func (x MessageType) String() string {
	return proto.EnumName(MessageType_name, int32(x))
}
func (x *MessageType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(MessageType_value, data, "MessageType")
	if err != nil {
		return err
	}
	*x = MessageType(value)
	return nil
}
func (MessageType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type ErrorCode int32

const (
	ErrorCode_EC_SERVICE1_BEGIN   ErrorCode = 1000
	ErrorCode_EC_NOT_AT_HOME      ErrorCode = 1001
	ErrorCode_EC_WEATHER_NOT_GOOD ErrorCode = 1002
	ErrorCode_EC_SERVICE1_END     ErrorCode = 2000
)

var ErrorCode_name = map[int32]string{
	1000: "EC_SERVICE1_BEGIN",
	1001: "EC_NOT_AT_HOME",
	1002: "EC_WEATHER_NOT_GOOD",
	2000: "EC_SERVICE1_END",
}
var ErrorCode_value = map[string]int32{
	"EC_SERVICE1_BEGIN":   1000,
	"EC_NOT_AT_HOME":      1001,
	"EC_WEATHER_NOT_GOOD": 1002,
	"EC_SERVICE1_END":     2000,
}

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}
func (x ErrorCode) String() string {
	return proto.EnumName(ErrorCode_name, int32(x))
}
func (x *ErrorCode) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ErrorCode_value, data, "ErrorCode")
	if err != nil {
		return err
	}
	*x = ErrorCode(value)
	return nil
}
func (ErrorCode) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type SayHelloRequest struct {
	Person           *uint32 `protobuf:"varint,1,req,name=person" json:"person,omitempty"`
	BlessMessage     *string `protobuf:"bytes,2,req,name=bless_message" json:"bless_message,omitempty"`
	Gift             *string `protobuf:"bytes,3,opt,name=gift" json:"gift,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SayHelloRequest) Reset()                    { *m = SayHelloRequest{} }
func (m *SayHelloRequest) String() string            { return proto.CompactTextString(m) }
func (*SayHelloRequest) ProtoMessage()               {}
func (*SayHelloRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *SayHelloRequest) GetPerson() uint32 {
	if m != nil && m.Person != nil {
		return *m.Person
	}
	return 0
}

func (m *SayHelloRequest) GetBlessMessage() string {
	if m != nil && m.BlessMessage != nil {
		return *m.BlessMessage
	}
	return ""
}

func (m *SayHelloRequest) GetGift() string {
	if m != nil && m.Gift != nil {
		return *m.Gift
	}
	return ""
}

type SayHelloResponse struct {
	Rc               *binggo.ResponseCode `protobuf:"bytes,1,req,name=rc" json:"rc,omitempty"`
	Feedback         *string              `protobuf:"bytes,2,opt,name=feedback" json:"feedback,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (m *SayHelloResponse) Reset()                    { *m = SayHelloResponse{} }
func (m *SayHelloResponse) String() string            { return proto.CompactTextString(m) }
func (*SayHelloResponse) ProtoMessage()               {}
func (*SayHelloResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *SayHelloResponse) GetRc() *binggo.ResponseCode {
	if m != nil {
		return m.Rc
	}
	return nil
}

func (m *SayHelloResponse) GetFeedback() string {
	if m != nil && m.Feedback != nil {
		return *m.Feedback
	}
	return ""
}

var E_SayHelloRequest = &proto.ExtensionDesc{
	ExtendedType:  (*binggo.Body)(nil),
	ExtensionType: (*SayHelloRequest)(nil),
	Field:         1000,
	Name:          "binggo.service1.say_hello_request",
	Tag:           "bytes,1000,opt,name=say_hello_request",
}

var E_SayHelloResponse = &proto.ExtensionDesc{
	ExtendedType:  (*binggo.Body)(nil),
	ExtensionType: (*SayHelloResponse)(nil),
	Field:         1001,
	Name:          "binggo.service1.say_hello_response",
	Tag:           "bytes,1001,opt,name=say_hello_response",
}

func init() {
	proto.RegisterType((*SayHelloRequest)(nil), "binggo.service1.SayHelloRequest")
	proto.RegisterType((*SayHelloResponse)(nil), "binggo.service1.SayHelloResponse")
	proto.RegisterEnum("binggo.service1.MessageType", MessageType_name, MessageType_value)
	proto.RegisterEnum("binggo.service1.ErrorCode", ErrorCode_name, ErrorCode_value)
	proto.RegisterExtension(E_SayHelloRequest)
	proto.RegisterExtension(E_SayHelloResponse)
}

var fileDescriptor0 = []byte{
	// 379 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x7c, 0x91, 0xcf, 0x8e, 0xda, 0x30,
	0x10, 0xc6, 0x05, 0xad, 0x9a, 0x32, 0x04, 0x12, 0x0c, 0x6d, 0xa3, 0x9e, 0xd2, 0x9e, 0x10, 0x87,
	0x08, 0x38, 0x72, 0xe3, 0x8f, 0x4b, 0x52, 0x41, 0xd2, 0x26, 0x69, 0xab, 0x9e, 0xac, 0x00, 0x26,
	0xa0, 0x52, 0x9c, 0xda, 0x74, 0xa5, 0xbc, 0xe5, 0x3e, 0x06, 0xec, 0x53, 0xac, 0x13, 0x82, 0x96,
	0xe5, 0xb0, 0x97, 0x91, 0xfc, 0x8d, 0xfd, 0xfb, 0x3c, 0xdf, 0x80, 0x21, 0x28, 0xbf, 0xdb, 0x2e,
	0x69, 0xcf, 0xea, 0x75, 0xbb, 0x5d, 0xab, 0x9f, 0x95, 0x84, 0xb3, 0x03, 0x43, 0xda, 0x62, 0xbb,
	0x8f, 0x63, 0x66, 0x5d, 0x2e, 0x7c, 0x54, 0x0b, 0x21, 0x6f, 0x7f, 0xfe, 0x02, 0x5a, 0x10, 0xa5,
	0x36, 0xdd, 0xed, 0x98, 0x4f, 0xff, 0xfd, 0xa7, 0xe2, 0x80, 0xea, 0xf0, 0x26, 0xa1, 0x5c, 0xb0,
	0xbd, 0x51, 0x32, 0xcb, 0xed, 0x1a, 0x7a, 0x07, 0xb5, 0xc5, 0x8e, 0x0a, 0x41, 0xfe, 0xca, 0x12,
	0xc5, 0xd4, 0x28, 0x4b, 0xb9, 0x82, 0x54, 0x78, 0x1d, 0x6f, 0xd7, 0x07, 0xe3, 0x95, 0x59, 0x6a,
	0x57, 0x24, 0x47, 0x7f, 0xe2, 0x88, 0x84, 0xed, 0x05, 0x45, 0x26, 0x94, 0xf9, 0x32, 0x87, 0x54,
	0xfb, 0x2d, 0xab, 0xb0, 0xbd, 0x74, 0xc7, 0x6c, 0x45, 0x91, 0x0e, 0x6f, 0xd7, 0x94, 0xae, 0x16,
	0xd1, 0xf2, 0x8f, 0xa4, 0x4a, 0x4e, 0x27, 0x82, 0xea, 0xfc, 0x6c, 0x13, 0xa6, 0x09, 0x45, 0x0d,
	0x50, 0x47, 0x78, 0xea, 0xb8, 0xae, 0xe3, 0x4e, 0x89, 0x33, 0xd1, 0x8f, 0x0a, 0x7a, 0x0f, 0x8d,
	0x60, 0xf8, 0x9b, 0xd8, 0x78, 0x36, 0xf3, 0x88, 0x8f, 0xbf, 0xff, 0xc0, 0x41, 0x98, 0xe9, 0x1f,
	0x00, 0x5d, 0xeb, 0xc1, 0x37, 0xcf, 0x0d, 0xb0, 0x7e, 0x52, 0xe4, 0x3c, 0x15, 0xec, 0x4e, 0x0a,
	0xc0, 0xbd, 0xd6, 0xd9, 0xc8, 0x33, 0xe7, 0x8c, 0xe7, 0x3f, 0x90, 0x34, 0x3c, 0x26, 0x01, 0xf6,
	0x7f, 0x3a, 0x63, 0xdc, 0x23, 0xb9, 0x59, 0x46, 0x6b, 0x42, 0x5d, 0xea, 0xae, 0x17, 0x92, 0x61,
	0x48, 0x6c, 0x6f, 0x9e, 0x93, 0x0c, 0x68, 0x4a, 0xf1, 0x17, 0x1e, 0x86, 0x36, 0xf6, 0xf3, 0xe6,
	0xd4, 0xf3, 0x26, 0xfa, 0x83, 0x82, 0x5a, 0xa0, 0x5d, 0x63, 0xa4, 0x9f, 0x74, 0x1a, 0x7c, 0x85,
	0x86, 0x88, 0x52, 0xb2, 0xc9, 0x52, 0x21, 0xbc, 0x88, 0x57, 0xbd, 0x24, 0x31, 0x62, 0xab, 0xd4,
	0x38, 0x2a, 0x72, 0xec, 0x6a, 0xdf, 0xb4, 0x6e, 0xd6, 0x64, 0xdd, 0x6c, 0x65, 0x30, 0x03, 0x74,
	0xcd, 0x2a, 0x22, 0x7e, 0x0e, 0x3b, 0x9d, 0x61, 0x9f, 0x5e, 0x80, 0x9d, 0xdf, 0x3d, 0x06, 0x00,
	0x00, 0xff, 0xff, 0xe6, 0x7d, 0x1b, 0x0f, 0x30, 0x02, 0x00, 0x00,
}
